
import * as d from './proxies';

export const DIRECTIVES = [
d.AppLogo,
  d.AppMegaMenu,
  d.AppNavigationMainMobile,
  d.AppNavigationSectorMobile,
  d.ScaleAccordion,
  d.ScaleAlert,
  d.ScaleAppHeader,
  d.ScaleAppShell,
  d.ScaleBreadcrumb,
  d.ScaleButton,
  d.ScaleCard,
  d.ScaleCarousel,
  d.ScaleChartStackCard,
  d.ScaleCollapsible,
  d.ScaleDivider,
  d.ScaleIcon,
  d.ScaleInput,
  d.ScaleLink,
  d.ScaleList,
  d.ScaleListItem,
  d.ScaleModal,
  d.ScaleProgressBar,
  d.ScaleSidebarNav,
  d.ScaleSidebarNavCollapsible,
  d.ScaleSidebarNavItem,
  d.ScaleSlider,
  d.ScaleSsrSlotFix,
  d.ScaleSwitch,
  d.ScaleTabHeader,
  d.ScaleTabNav,
  d.ScaleTabPanel,
  d.ScaleTable,
  d.ScaleTag,
  d.ScaleText,
  d.ScaleToast
];
