import { JssStyle } from 'jss';
import { getTransition } from '../../theme/helpers';

export const styles: JssStyle = {
  button: {
    color: ({ colors }) => colors.common.black,
    '--icon-color': ({ colors }) => colors.common.black,
    background: ({ colors }) => colors.grey[300],
    border: ({ colors }) => `1px solid ${colors.grey[300]}`,
    borderRadius: ({ shape }) => shape.borderRadius,
    fontSize: ({ typography }) => typography.variants.button.fontSize,
    fontWeight: ({ typography }) =>
      typography.variants.button.fontWeightRegular,
    textTransform: ({ typography }) => typography.variants.button.textTransform,
    letterSpacing: ({ typography }) => typography.variants.button.letterSpacing,
    transition: theme => getTransition(theme, 'all', 'shorter', 'easeInOut'),
    boxSizing: 'border-box',
    position: 'relative',
    display: 'inline-flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    verticalAlign: 'middle',
    textAlign: 'center',
    cursor: 'pointer',
    userSelect: 'none',
    padding: '1px 16px',
    boxShadow: 'none',
    textDecoration: 'none',
    fontFamily: 'TeleNeoWeb-Bold',
    paddingLeft: 22,
    paddingRight: 22,
    paddingTop: 8,
    paddingBottom: 8,
    height: 'unset',
    minHeight: 40,
    lineHeight: '24px',
    whiteSpace: 'nowrap',
    '&:before': {
      width: 0,
      content: '""',
      display: 'block',
      height: '100%',
    },
    '&:hover': {
      transition: theme => getTransition(theme, 'all', 'standard', 'easeInOut'),
      boxShadow: 'none',
      textDecoration: 'none',
      borderColor: ({ palette }) => palette.magentaHover,
      background: ({ palette }) => palette.magentaHover,
      color: ({ palette }) => palette.white,
      '--icon-color': ({ palette }) => palette.white,
    },
    '&, &:focus': {
      borderColor: ({ palette }) => palette.magenta,
      background: ({ palette }) => palette.magenta,
      color: ({ palette }) => palette.white,
      '--icon-color': ({ palette }) => palette.white,
    },
    '&:active, &.selected': {
      borderColor: ({ palette }) => palette.magentaActive,
      background: ({ palette }) => palette.magentaActive,
      color: ({ palette }) => palette.white,
      '--icon-color': ({ palette }) => palette.white,
    },
  },
  'button--disabled': {
    '&, &:hover': {
      cursor: 'not-allowed',
      background: ({ palette }) => palette.grayDisabledBackground,
      border: ({ outlines }) => outlines.disabled,
      color: ({ palette }) => palette.grayDisabled,
      '--icon-color': ({ palette }) => palette.grayDisabled,
      opacity: 1,
    },
    '&$button--variant-secondary, &$button--variant-secondary:hover': {
      background: 'none',
      border: ({ outlines }) => outlines.disabled,
      color: ({ palette }) => palette.grayDisabled,
      '--icon-color': ({ palette }) => palette.grayDisabled,
    },
  },
  button__before: {
    marginRight: '.5rem',
    display: 'flex',
    alignItems: 'center',
  },
  button__after: {
    marginLeft: '.5rem',
    display: 'flex',
    alignItems: 'center',
  },
  'button--icon-only': {
    height: 42,
    width: 42,
    padding: 0,
  },
  'button--variant-secondary': {
    '&, &:focus, &.focus': {
      borderColor: ({ palette }) => palette.gray,
      background: 'none',
      color: ({ palette }) => palette.gray,
      '--icon-color': ({ palette }) => palette.gray,
    },
    '&:hover, &.hover': {
      borderColor: ({ palette }) => palette.magentaHover,
      background: 'none',
      color: ({ palette }) => palette.magentaHover,
      '--icon-color': ({ palette }) => palette.magentaHover,
    },
    '&:active, &.active, &.selected': {
      borderColor: ({ palette }) => palette.magentaActive,
      background: 'none',
      color: ({ palette }) => palette.magentaActive,
      '--icon-color': ({ palette }) => palette.magentaActive,
    },
  },
  'button--size-small': {
    minHeight: 32,
    fontSize: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 4,
    paddingBottom: 4,
    lineHeight: '16px',
    '&$button--icon-only': {
      height: 32,
      width: 32,
      padding: 0,
    },
  },
};
