import { JssStyle } from 'jss';
import { getTransition } from '../../theme/helpers';

export const styles: JssStyle = {
  button: {
    color: ({ colors }) => colors.common.black,
    '--icon-color': ({ colors }) => colors.common.black,
    background: ({ colors }) => colors.grey[300],
    border: ({ colors }) => `1px solid ${colors.grey[300]}`,
    borderRadius: ({ shape }) => shape.borderRadius,
    fontSize: ({ typography }) => typography.variants.button.fontSize,
    fontWeight: ({ typography }) =>
      typography.variants.button.fontWeightRegular,
    textTransform: ({ typography }) => typography.variants.button.textTransform,
    letterSpacing: ({ typography }) => typography.variants.button.letterSpacing,
    transition: theme => getTransition(theme, 'all', 'shorter', 'easeInOut'),
    boxSizing: 'border-box',
    position: 'relative',
    display: 'inline-flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    verticalAlign: 'middle',
    textAlign: 'center',
    cursor: 'pointer',
    userSelect: 'none',
    padding: '1px 16px',
    boxShadow: 'none',
    textDecoration: 'none',
    fontFamily: 'TeleNeoWeb-Bold',
    paddingLeft: 22,
    paddingRight: 22,
    paddingTop: 8,
    paddingBottom: 8,
    height: 'unset',
    minHeight: 40,
    lineHeight: '24px',
    whiteSpace: 'nowrap',
    '&:before': {
      width: 0,
      content: '""',
      display: 'block',
      height: '100%',
    },
    '&:hover': {
      transition: theme => getTransition(theme, 'all', 'standard', 'easeInOut'),
      boxShadow: 'none',
      textDecoration: 'none',
      borderColor: '#F90984',
      background: '#F90984',
      color: '#fff',
      '--icon-color': '#fff',
    },
    '&, &:focus': {
      borderColor: '#e20074',
      background: '#e20074',
      color: '#fff',
      '--icon-color': '#fff',
    },
    '&:active, &.selected': {
      borderColor: '#CB0068',
      background: '#CB0068',
      color: '#fff',
      '--icon-color': '#fff',
    },
  },
  'button--disabled': {
    '&, &:hover': {
      cursor: 'not-allowed',
      background: '#D0D0D0',
      border: '1px solid #D0D0D0',
      color: '#A4A4A4',
      '--icon-color': '#A4A4A4',
      opacity: 1,
    },
    '&$button--variant-secondary, &$button--variant-secondary:hover': {
      background: 'none',
      border: '1px solid #CDCDCD',
      color: '#CDCDCD',
      '--icon-color': '#cdcdcd',
    },
  },
  button__before: {
    marginRight: '.5rem',
    display: 'flex',
    alignItems: 'center',
  },
  button__after: {
    marginLeft: '.5rem',
    display: 'flex',
    alignItems: 'center',
  },
  'button--icon-only': {
    height: 42,
    width: 42,
    padding: 0,
  },
  'button--variant-secondary': {
    '&, &:focus, &.focus': {
      borderColor: '#111111',
      background: 'none',
      color: '#161616',
      '--icon-color': '#161616',
    },
    '&:hover, &.hover': {
      borderColor: '#E20074',
      background: 'none',
      color: '#E20074',
      '--icon-color': '#e20074',
    },
    '&:active, &.active, &.selected': {
      borderColor: '#CB0068',
      background: 'none',
      color: '#CB0068',
      '--icon-color': '#cb0068',
    },
  },
  'button--size-small': {
    minHeight: 32,
    fontSize: 12,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 4,
    paddingBottom: 4,
    lineHeight: '16px',
    '&$button--icon-only': {
      height: 32,
      width: 32,
      padding: 0,
    },
  },
};
